name: pixel_adventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:

  flutter_launcher_icons: ^0.13.1
  flame: ^1.15.0
  flame_tiled: ^1.18.4
  flutter:
    sdk: flutter
  flame_audio: ^1.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
     - family: Hind
       fonts:
         - asset: assets/fonts/Hind/charybdis.regular.ttf
         - weight: 300

  uses-material-design: true
  assets:
     - assets/fonts/Hind/
     - assets/tiles/
     - assets/images/Enemies/Plant/
     - assets/images/Terrain/
     - assets/images/Menu/Buttons/
     - assets/images/Main Characters/Ninja Frog/
     - assets/images/Main Characters/Pink Man/
     - assets/images/Main Characters/Mask Dude/
     - assets/images/Main Characters/Virtual Guy/
     - assets/images/HUD/
     - assets/audio/
     - assets/images/Background/
     - assets/images/Items/Fruits/
     - assets/images/Traps/Saw/
     - assets/images/Main Characters/
     - assets/images/Items/Checkpoints/Checkpoint/
     - assets/images/Traps/Trampoline/
     - assets/images/Menu/Text/
     - assets/images/Menu/Text/Text (White) (8x10).png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

  min_sdk_android: 21 
